@echo off

title ------------learn-bat-----------

mode 110,60

set /a "x = 0"
set /a "flag = 0"

:more_to_process
    if %x% leq 100 (
        timeout /t 2
        echo %x%

        if %flag%==0 (color 4a) else (color 1e)
        if %flag%==0 (set /a "flag = 1") else (set /a "flag = 0")

        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGP5Y?7~^^^^^~!!7?JYPGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBGJ?!~^.  ..::^^~~~!!77JYPBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB5?7!~:. ..::^^^~~!!777??JYPBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBY?7!^:. ..::^^~~~!!77???JJYPBBG5PGBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBPJ?!~^. ..:::^^~~!!!77??JJYYGBB5YYYYYYPGBB###BBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBB5?7!~:. ..::^^~~~!!777??JJY5BBBYYYYJ?7777?JY5PGGGBBBBBGGGPGBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBGJ?7~^:  ..::^^~~!!!77???JJYGBBPYYYJJ?77!!~~^^^^^^^^^^~!!7JGBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBPJ7!~^. ..:::^^~~!!777??JJY5BBB5YYYJ??77!!!~~^^::..  :^~7?5BBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBB5?7!~:. ..::^^~~~!!777??JJYPBBGYYYYJ??77!!~~^^^::.. .:~!7JPBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBGJ?7~^:  ..::^^~~!!!77???JYYGBBPYYYJJ?777!!~~^^:::.. :^~7?YBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBPJ7!~:.  ..::^^~~!!777??JJY5BBB5YYYJ??77!!!~~^^::.. .:^!7J5BBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBYJ7!!~^^~~~~!!!!!!!!77??JJYPBBGYYYYJ?777!!~~^^^::.. .^~!?JPBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGGP5YJ??JJYGBBPYYYJ??77!!!~~^^:::.. :^~7?YBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBGGPY?!^^^~~!77?JY5PGB##BG5Y5BBBYYYYJ??77!!~~~^^::.. .:^!7J5BBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBP5J?!^. .:^^~!!77??JJY5PBB#BGBBB5YYJJ?777!!~~^^^::.. .^~!?JGBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBB5YJ?!^...:^~~!77??JJYYY55PBBBBB##BGPY?77!!!~~^^::..  :^!7?YBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBG5YJ7~: .:^^~!!77??JJYY555PPB#B7?YPB##BPY?7!~^^:::.. .:^!7YPBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBPYJ?!^. .:^~~!!7??JJJYY555PG##P::::^!J5GBBBGPY?7!~^^^~7YPGBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBB5YJ?!^..::^~~!77??JJYYY55PPB##?::::....:^!7J5PGGBBBBBBGG5YBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBP5Y?7~: .:^^~!!77??JJYY555PPB#B~:::::........ ...::::::::.~BBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBB5YJ?!^. .:^~~!77??JJJYY55PPG##5:::::...........       ...:Y#BBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBG5YJ7!^..::^~~!77??JJYYY55PPB##7:::::...........      ...:^GBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBP5Y?7~: .:^^~!!77??JJYY555PPB#G^:::::..........       ...:7BBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBB5YJ?!^. .:^^~!!7??JJJYY55PPG##Y:::::...........      ....:5#BBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBG5YJ?7!^~~!!777????JJJYY55PPB##!:::::...........      ...:^BBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBB#BB#BBBBBBBBBBBBBBBBB##BBBBBBBBBGGPP55555PPB#G^:::::..........       ...:?#BBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBG5BG5GBBBBBBBBBBBBBB#PPGBBBBBBBBBBBBBBBBGPPG##J:::::...........      ....:P#BBBBBBBBBBBBBBBBBBBB"
        echo  "BBB#5!PJ!YYY5YJY5Y5JY5Y5Y7J?#BBBBBBBBBBBBBBBBBBBBBY!^:............       ...:~BBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBP5J5YY5Y5YPPYY5YJ5Y55YPYBBBBBBBBBBBBBBBBBBBBBB#BGY7^..........      ....:J#BBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBGBBBBBBBGBBGBBBBBBBBBBBBBBBBBBBBBBBBBBB##BPJ!^:...         ..:~GBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBB#7.5#BB#Y..J#BBBG:!#J:PBBBBB###BBBBBBB###G:!BBBBB######BG5J?!~^^::^~7?YGB#B#BBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBP ~#BBB:~!.GBB#7 5#G5GBBPBGP5PG#BBB#G55PG ^BBB#GP55GBBBGG####GGBBB#GG##GP55GBBBB5PG5GP555GBBBBB"
        echo  "BBBBB#7 PB#? PG !#BG !##? 5#P.~!77~.?BBG~^7?7~ ~BBP~^7?7^~P#!.PB#5 .P##5 JB7^7?7^^PBBG?7P#JJP?5BBBBB"
        echo  "BBBBBBG.!#G.!##? 5#7 PB#? 5#P ~B##B:.GB^.P###5 ~#G.:G###G:.GG.~#B^~:~#B^:BG.:YPGGYGBB5YYJBJYGGBBBBBB"
        echo  "BBBBBB#? G7.GBBB.~G 7#B#? 5#P 7#BB#~.GG ^#BBB#:^#5 7#BBB#7 5#J 5Y PY PJ 5#BGJ!~^^~YBBGBBGGGBBBBBBBBB"
        echo  "BBBBBBBG.~ ?#BB#J ^.GBB#? 5#5 7#BBB^.GB! YBBBY ^#B^.5BBB5.^BBB^::!#B::.7#BP~JB#BP :BBBBBBBBBBBBBBBBB"
        echo  "BBBBBBB#J:~BBBBBB~.J#BB#J:5#P:?#BBB!^GBBJ~~!!7^!BBG?~!!!~?GBB#P:^GB#Y:^GBBBJ^~!!~!PBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB#BGGB#BBBBB#BGGGB#BBBBBBBBBBBBBBBBB#BBGGB##BBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        echo  ""

        set /a "x = x + 1"

        goto :more_to_process
    )

pause